/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p1;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Situ Singh
 */
public class admAdd extends javax.swing.JFrame {

    /**
     * Creates new form admAdd
     */
    public admAdd() {
        initComponents();
        Color c=new Color(0,102,153);
        this.getContentPane().setBackground(c);
        btnUpdate2.setVisible(false);
        t5.setSelectedItem(null);
        btnhide.setVisible(false);
        label.setVisible(false);
        final op opr=new op();
        t4.getEditor().getEditorComponent().addKeyListener(new KeyAdapter(){
            
            @Override
            public void keyReleased(KeyEvent evt){
                String a=t4.getEditor().getItem().toString();
                if(evt.getKeyCode()>=65 && evt.getKeyCode()<=90 || evt.getKeyCode()>=96 && evt.getKeyCode()<=105 || evt.getKeyCode()==8){
                    t4.setModel(opr.getList3(a));
                    if(t4.getItemCount()>0){
                        t4.showPopup();
                        if(evt.getKeyCode()!=8){
                            ((JTextComponent)t4.getEditor().getEditorComponent()).select(a.length(), t4.getEditor().getItem().toString().length());
                        }
                        else{
                            t4.getEditor().setItem(a);
                        }
                    }else{
                        t4.addItem(a);
                    }
                }
            }
        });
    }
    String letterno;
    public admAdd(String lno){
        initComponents();
        Color c=new Color(0,102,153);
        this.getContentPane().setBackground(c);
        letterno=lno;
        btnadd.setVisible(false);
        btnhide.setVisible(false);
        label.setVisible(false);
        btnhide.doClick();
        t1.setEnabled(false);
        t2.setEnabled(false);
        t3.setEnabled(false);
        t4.setEnabled(false);
        t5.setEnabled(false);
        cmb1.setEnabled(false);
        c2.setEnabled(false);
        img.setVisible(false);
        btn.setVisible(false);
        l18.setVisible(false);
       }
            String sql;	   
            static Connection conn = null;	   

            Statement stmt = null;
            String ff=null;
            int s=0;
            byte[] person_image=null;
            BufferedImage im;
            File image;       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l12 = new javax.swing.JLabel();
        btnUpdate2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        t1 = new com.toedter.calendar.JDateChooser();
        t5 = new javax.swing.JComboBox();
        t3 = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        t4 = new javax.swing.JComboBox();
        l10 = new javax.swing.JLabel();
        l13 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t6 = new javax.swing.JTextArea();
        l11 = new javax.swing.JLabel();
        ch1 = new javax.swing.JCheckBox();
        l17 = new javax.swing.JLabel();
        c2 = new javax.swing.JCheckBox();
        img = new javax.swing.JTextField();
        cmb1 = new javax.swing.JComboBox();
        l18 = new javax.swing.JLabel();
        btnhide = new javax.swing.JButton();
        btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        l16 = new javax.swing.JLabel();
        t9 = new com.toedter.calendar.JDateChooser();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        l12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l12.setForeground(new java.awt.Color(255, 255, 255));
        l12.setText("Received From");

        btnUpdate2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnUpdate2.setText("UPDATE");
        btnUpdate2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 0, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        btnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD DAK ENTRY");

        l9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l9.setForeground(new java.awt.Color(255, 255, 255));
        l9.setText("Subject *");

        l1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("Date *");

        t1.setDateFormatString("yyyy-MM-dd");
        t1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        t5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Establishment NI", "Establishment Industrial", "Discipline", "Employability", "Finance", "PA to Col. ADM", "CR" }));

        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnadd.setText("ADD ENTRY");
        btnadd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 0, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        t4.setEditable(true);
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        l10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l10.setForeground(new java.awt.Color(255, 255, 255));
        l10.setText("Letter No. *");

        l13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l13.setForeground(new java.awt.Color(255, 255, 255));
        l13.setText("Section");

        panel2.setBackground(new java.awt.Color(204, 204, 255));

        t6.setColumns(20);
        t6.setRows(5);
        jScrollPane2.setViewportView(t6);

        l11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l11.setText("Remarks");

        ch1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ch1.setText("Cmdt");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(l11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ch1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(ch1)
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addComponent(l11)
                        .addGap(52, 52, 52))))
        );

        l17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l17.setForeground(new java.awt.Color(255, 255, 255));
        l17.setText("Priority");

        c2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.setText("CONFIDENTIAL");

        img.setEditable(false);

        cmb1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NORMAL", "FSD" }));

        l18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l18.setForeground(new java.awt.Color(255, 255, 255));
        l18.setText("Upload Image");

        btnhide.setText("ddd");
        btnhide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhideActionPerformed(evt);
            }
        });

        btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn.setText("BROWSE");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        l16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l16.setForeground(new java.awt.Color(255, 255, 255));
        l16.setText("Reminder");

        t9.setDateFormatString("yyyy-MM-dd");
        t9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        t9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t9KeyTyped(evt);
            }
        });

        label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label.setForeground(new java.awt.Color(255, 0, 0));
        label.setText("* Choose correct reminder date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(748, 748, 748)
                        .addComponent(btnhide))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l17, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t3)
                            .addComponent(t2)
                            .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(l16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(l18, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn)))))))
                .addContainerGap(333, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(496, 496, 496))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l1)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(l10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l9)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l12)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l17)
                    .addComponent(l18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(c2)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(btnhide)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate2ActionPerformed
        try
        {
            String JDBC_DRIVER = "com.mysql.jdbc.Driver";
            String DB_URL = "jdbc:mysql://localhost/dak";
            String USER = "root";
            String PASS = "root";
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(DB_URL,USER,PASS);
            sql="update adm set remarks=?,reminder=?,cmdt=? where letterno=?";
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1,t6.getText());
            java.util.Date d;
            d = t1.getDate();
            java.util.Date d2=t9.getDate();
            if(d2==null){
                  pst.setString(2,null);
            }
            else if(d.compareTo(d2)<0){
                  pst.setString(2,((JTextField)t9.getDateEditor().getUiComponent()).getText());
            }
            else{
                label.setVisible(true);
                t9.setDate(null);
            } 
            if(ch1.isSelected()){
                 pst.setString(3,"Y");
            }
            else
                 pst.setString(3,"N");
            pst.setString(4,t2.getText());
            pst.execute();
            t1.setDate(null);
            t2.setText("");
            t3.setText("");
            t4.setSelectedItem(null);
            t5.setSelectedItem(null);
            t9.setDate(null);
            t6.setText("");
            label.setVisible(false);
            cmb1.setSelectedIndex(0);
            c2.setSelected(false);
            ch1.setSelected(false);
            JOptionPane.showMessageDialog(this,"Entry updated successfully!!!");
            this.setVisible(false);
        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_btnUpdate2ActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        try
        {
            String JDBC_DRIVER = "com.mysql.jdbc.Driver";
            String DB_URL = "jdbc:mysql://localhost/dak";
            String USER = "root";
            String PASS = "root";
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(DB_URL,USER,PASS);
            sql="insert into adm values(?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1,((JTextField)t1.getDateEditor().getUiComponent()).getText());
            pst.setString(2,t2.getText());
            pst.setString(3,t3.getText());
            pst.setString(4,(String)t4.getSelectedItem());
            pst.setString(5,(String)t5.getSelectedItem());
            pst.setString(6,t6.getText());
            java.util.Date d;
            d = t1.getDate();
            java.util.Date d2=t9.getDate();
            if(d2==null){
                  pst.setString(10,null);
            }
            else if(d.compareTo(d2)<0){
                  pst.setString(10,((JTextField)t9.getDateEditor().getUiComponent()).getText());
            }
            else{
                label.setVisible(true);
                t9.setDate(null);
            }   
            
            int i=cmb1.getSelectedIndex();
            if(i==1)
            pst.setString(7,"Y");
            else
            pst.setString(7,"N");
            if(c2.isSelected())
            pst.setString(8,"Y");
            else
            pst.setString(8,"N");
            if(ff!=null){
            image=new File(ff) ;
            FileInputStream fis;
            fis=new FileInputStream(image);
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[] buf=new byte[4096];
            for(int k;(k=fis.read(buf))!=-1;){
                bos.write(buf,0,k);
            }
            person_image=bos.toByteArray();
            pst.setBytes(9,person_image);
            }
            else
                pst.setString(9,null);
            if(ch1.isSelected()){
                 pst.setString(10,"Y");
            }
            else
                 pst.setString(10,"N");
            pst.execute();
            t1.setDate(null);
            t2.setText("");
            t3.setText("");
            t4.setSelectedItem(null);
            t5.setSelectedItem(null);
            t6.setText("");
            t9.setDate(null);
            label.setVisible(false);
            cmb1.setSelectedIndex(0);
            c2.setSelected(false);
            img.setText("");
            ch1.setSelected(false);
            JOptionPane.showMessageDialog(this,"Entry added successfully!!!");

        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ogAdd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(admAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
      
    }//GEN-LAST:event_t4ActionPerformed

    private void btnhideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhideActionPerformed

        try
        {
            String JDBC_DRIVER = "com.mysql.jdbc.Driver";
            String DB_URL = "jdbc:mysql://localhost/dak";
            String USER = "root";
            String PASS = "root";
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(DB_URL,USER,PASS);
            stmt=conn.createStatement();
            sql="select * from adm where letterno = '"+letterno+"';";
            ResultSet rs=stmt.executeQuery(sql);
            int i=0;
            while(rs.next()){
                t2.setText(rs.getString("letterno"));
                t1.setDate(rs.getDate("date"));
                String sub=rs.getString("subject");

                t3.setText(sub);
                t4.addItem(rs.getString("recv_from"));
                t5.addItem(rs.getString("to_whom"));
                t6.setText(rs.getString("remarks"));
                if("Y".equals(rs.getString("p")))
                cmb1.setSelectedIndex(1);
                if("Y".equals(rs.getString("c")))
                c2.setSelected(true);
                t9.setDate(rs.getDate("reminder"));
                if(rs.getString("cmdt").equals("Y")){
                    ch1.setSelected(true);
                }
            }
        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e.getStackTrace());
        }
    }//GEN-LAST:event_btnhideActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        JFileChooser f= new JFileChooser();
        int result=f.showOpenDialog(this);
        ff=f.getSelectedFile().getAbsolutePath();
        img.setText(ff);
    }//GEN-LAST:event_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t9KeyTyped

    }//GEN-LAST:event_t9KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new admAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btnUpdate2;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnhide;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox ch1;
    private javax.swing.JComboBox cmb1;
    private javax.swing.JTextField img;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l9;
    private javax.swing.JLabel label;
    private java.awt.Panel panel2;
    private com.toedter.calendar.JDateChooser t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JComboBox t4;
    private javax.swing.JComboBox t5;
    private javax.swing.JTextArea t6;
    private com.toedter.calendar.JDateChooser t9;
    // End of variables declaration//GEN-END:variables
}
