package p1;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Situ Singh
 */
public class ogAdd extends javax.swing.JFrame {

    /**
     * Creates new form ogAdd
     */
    public ogAdd() {
        
        initComponents();
        Color c=new Color(0,102,153);
        this.getContentPane().setBackground(c);
        label.setVisible(false);
        btnUpdate.setVisible(false);
        t5.setSelectedItem(null);
        btnhide.setVisible(false);
        final op opr=new op();
        t4.getEditor().getEditorComponent().addKeyListener(new KeyAdapter(){
            
            @Override
            public void keyReleased(KeyEvent evt){
                String a=t4.getEditor().getItem().toString();
                if(evt.getKeyCode()>=65 && evt.getKeyCode()<=90 || evt.getKeyCode()>=96 && evt.getKeyCode()<=105 || evt.getKeyCode()==8){
                    t4.setModel(opr.getList2(a));
                    if(t4.getItemCount()>0){
                        t4.showPopup();
                        if(evt.getKeyCode()!=8){
                            ((JTextComponent)t4.getEditor().getEditorComponent()).select(a.length(), t4.getEditor().getItem().toString().length());
                        }
                        else{
                            t4.getEditor().setItem(a);
                        }
                    }else{
                        t4.addItem(a);
                    }
                }
            }
        });
    }
    
    String letterno;
    
    
    public ogAdd(String lno){
        initComponents();
        Color c=new Color(0,102,153);
        this.getContentPane().setBackground(c);
        letterno=lno;
        btnadd.setVisible(false);
        btnhide.setVisible(false);
        label.setVisible(false);
        btnhide.doClick();
       t1.setEnabled(false);
        t2.setEnabled(false);
        t3.setEnabled(false);
        t4.setEnabled(false);
        t5.setEnabled(false);
        cmb1.setEnabled(false);
        c2.setEnabled(false);
        img.setVisible(false);
        btn.setVisible(false);
        l18.setVisible(false);
        
       }
    
            String sql;	   
            static Connection conn = null;	   

            Statement stmt = null;
            String ff=null;
            int s=0;
            byte[] person_image=null;
            BufferedImage im;
            File image;     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        l13 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jScrollPane3 = new javax.swing.JScrollPane();
        t7 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        t8 = new javax.swing.JTextArea();
        l11 = new javax.swing.JLabel();
        l14 = new javax.swing.JLabel();
        l15 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        chwm = new javax.swing.JCheckBox();
        chcmdt = new javax.swing.JCheckBox();
        l16 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        t9 = new com.toedter.calendar.JDateChooser();
        l12 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        t1 = new com.toedter.calendar.JDateChooser();
        t3 = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        t4 = new javax.swing.JComboBox();
        t5 = new javax.swing.JComboBox();
        label = new javax.swing.JLabel();
        btnhide = new javax.swing.JButton();
        c2 = new javax.swing.JCheckBox();
        l17 = new javax.swing.JLabel();
        cmb1 = new javax.swing.JComboBox();
        img = new javax.swing.JTextField();
        l18 = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        l13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l13.setForeground(new java.awt.Color(255, 255, 255));
        l13.setText("Group Marker");

        panel2.setBackground(new java.awt.Color(204, 204, 255));

        t7.setColumns(20);
        t7.setRows(5);
        jScrollPane3.setViewportView(t7);

        t8.setColumns(20);
        t8.setRows(5);
        jScrollPane2.setViewportView(t8);

        l11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l11.setText("Cmdt. Remarks");

        l14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l14.setText("WM Remarks");

        l15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l15.setText("Approved By");

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rb1.setText("Yes");

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rb2.setText("No");

        chwm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        chwm.setText("WM");

        chcmdt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        chcmdt.setText("Cmdt");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(l15, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l11, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(rb1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(rb2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(240, Short.MAX_VALUE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addComponent(chcmdt)
                                .addGap(61, 61, 61)
                                .addComponent(chwm))
                            .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l15)
                    .addComponent(rb1)
                    .addComponent(rb2))
                .addGap(30, 30, 30)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chcmdt)
                    .addComponent(chwm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addComponent(l14)
                        .addGap(32, 32, 32)))
                .addGap(12, 12, 12)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addComponent(l11)
                        .addGap(31, 31, 31))))
        );

        l16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l16.setForeground(new java.awt.Color(255, 255, 255));
        l16.setText("Reminder");

        l10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l10.setForeground(new java.awt.Color(255, 255, 255));
        l10.setText("Letter No. *");

        t9.setDateFormatString("yyyy-MM-dd");
        t9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        l12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l12.setForeground(new java.awt.Color(255, 255, 255));
        l12.setText("Received From");

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 0, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADD DAK ENTRY");

        l9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l9.setForeground(new java.awt.Color(255, 255, 255));
        l9.setText("Subject *");

        l1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("Date *");

        t1.setDateFormatString("yyyy-MM-dd");
        t1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnadd.setText("ADD ENTRY");
        btnadd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 0, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255)));
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        t4.setEditable(true);
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        t5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MCO", "GEG", "TT CELL", "QA", "WSG" }));

        label.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        label.setForeground(new java.awt.Color(255, 0, 0));
        label.setText("* Choose correct reminder date");

        btnhide.setText("ddd");
        btnhide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhideActionPerformed(evt);
            }
        });

        c2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.setText("CONFIDENTIAL");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        l17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l17.setForeground(new java.awt.Color(255, 255, 255));
        l17.setText("Priority");

        cmb1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NORMAL", "FSD" }));

        img.setEditable(false);

        l18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l18.setForeground(new java.awt.Color(255, 255, 255));
        l18.setText("Upload Image");

        btn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn.setText("BROWSE");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(466, 466, 466))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(40, 40, 40))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(748, 748, 748)
                        .addComponent(btnhide))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(315, 315, 315)
                                .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(l10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(l9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(l12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(l17, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(l13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(t3)
                                    .addComponent(t2)
                                    .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(t4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(t5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(l18, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(l16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l1)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(l10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l9)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l12)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l13))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l17)))
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(c2)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(btnhide)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try
        {
            String JDBC_DRIVER = "com.mysql.jdbc.Driver";
            String DB_URL = "jdbc:mysql://localhost/dak";
            String USER = "root";
            String PASS = "root";
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(DB_URL,USER,PASS);
            sql="update other set approved_by=?,wm_rem=?,cmdt_rem=?,reminder=?,wm=?,cmdt=? where letterno=?";
            PreparedStatement pst=conn.prepareStatement(sql);
            if(rb1.isSelected())
                pst.setString(1,"Y");
            else if(rb2.isSelected())
                pst.setString(1,"N");
            else
                pst.setString(1,null);
            pst.setString(2,t7.getText());
            pst.setString(3,t8.getText());
            java.util.Date d;
            d = t1.getDate();
            java.util.Date d2=t9.getDate();
            if(d2==null){
                  pst.setString(4,null);
            }
            else if(d.compareTo(d2)<0){
                  pst.setString(4,((JTextField)t9.getDateEditor().getUiComponent()).getText());
            }
            else{
                label.setVisible(true);
                t9.setDate(null);
            }  
            if(chcmdt.isSelected()){
                pst.setString(5,"Y");
            }
            else{
                pst.setString(5,"N");
            }
            if(chwm.isSelected()){
                pst.setString(6,"Y");
            }
            else{
                pst.setString(6,"N");
            }
            pst.setString(7,t2.getText());
            pst.execute();
            t1.setDate(null);
            t2.setText("");
            t3.setText("");
            t4.setSelectedItem(null);
            t5.setSelectedItem(null);
            t7.setText("");
            t8.setText("");            
            t9.setDate(null);
            cmb1.setSelectedIndex(0);
            c2.setSelected(false);
            rb1.setSelected(false);
            rb2.setSelected(false);
            label.setVisible(false);
            chwm.setSelected(false);
            chcmdt.setSelected(false);
            JOptionPane.showMessageDialog(this,"Entry updated successfully!!!");
            this.setVisible(false);
        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        try
        {
            String JDBC_DRIVER = "com.mysql.jdbc.Driver";
            String DB_URL = "jdbc:mysql://localhost/dak";
            String USER = "root";
            String PASS = "root";
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(DB_URL,USER,PASS);
            sql="insert into other values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst=conn.prepareStatement(sql);
            pst.setString(1,((JTextField)t1.getDateEditor().getUiComponent()).getText());
            pst.setString(2,t2.getText());
            pst.setString(3,t3.getText());
            pst.setString(4,(String)t4.getSelectedItem());
            pst.setString(5,(String)t5.getSelectedItem());
            if(rb1.isSelected())
                pst.setString(6,"Y");
            else if(rb2.isSelected())
                pst.setString(6,"N");
            else
                pst.setString(6,null);
            pst.setString(7,t7.getText());
            pst.setString(8,t8.getText());
             java.util.Date d;
            d = t1.getDate();
            java.util.Date d2=t9.getDate();
            if(d2==null){
                  pst.setString(9,null);
            }
            else if(d.compareTo(d2)<0){
                  pst.setString(9,((JTextField)t9.getDateEditor().getUiComponent()).getText());
            }
            else{
                label.setVisible(true);
                t9.setDate(null);
            }   
            int i=cmb1.getSelectedIndex();
            if(i==1)
                pst.setString(10,"Y");
            else
                pst.setString(10,"N");
            if(c2.isSelected()){
                pst.setString(11,"Y");
                pst.setString(12,null);
            }
            
            else{
                pst.setString(11,"N");
                if(ff!=null){
            image=new File(ff) ;
            FileInputStream fis;
            fis=new FileInputStream(image);
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[] buf=new byte[4096];
            for(int k;(k=fis.read(buf))!=-1;){
                bos.write(buf,0,k);
            }
            person_image=bos.toByteArray();
            pst.setBytes(12,person_image);
            }
            else
                pst.setString(12,null);
            }
            if(chcmdt.isSelected()){
                pst.setString(13,"Y");
            }
            else{
                pst.setString(13,"N");
            }
            if(chwm.isSelected()){
                pst.setString(14,"Y");
            }
            else{
                pst.setString(14,"N");
            }
            pst.execute();
            buttonGroup1.clearSelection();
            t1.setDate(null);
            t2.setText("");
            t3.setText("");
            t4.setSelectedItem(null);
            t5.setSelectedItem(null);
            t7.setText("");
            t8.setText("");
            t9.setDate(null);
            cmb1.setSelectedIndex(0);
            c2.setSelected(false);
            l18.setVisible(true);
            btn.setVisible(true);
            img.setVisible(true);
            label.setVisible(false);
            img.setText("");
            chwm.setSelected(false);
            chcmdt.setSelected(false);
            JOptionPane.showMessageDialog(this,"Entry added successfully!!!");
            
            
        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ogAdd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ogAdd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnhideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhideActionPerformed

        try
        {
            String JDBC_DRIVER = "com.mysql.jdbc.Driver";
            String DB_URL = "jdbc:mysql://localhost/dak";
            String USER = "root";
            String PASS = "root";
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(DB_URL,USER,PASS);
            stmt=conn.createStatement();
            sql="select * from other where letterno = '"+letterno+"';";
            ResultSet rs=stmt.executeQuery(sql);
            int i=0;
            while(rs.next()){
                t2.setText(rs.getString("letterno"));
                t1.setDate(rs.getDate("date"));
                String sub=rs.getString("subject");

                t3.setText(sub);
                t4.addItem(rs.getString("recv_from"));
                t5.addItem(rs.getString("grp"));
                String r=rs.getString("approved_by");
                if(null != r)
                    switch (r) {
                    case "Y":
                        rb1.setSelected(true);
                        break;
                    case "N":
                        rb2.setSelected(true);
                        break;
                }
                t7.setText(rs.getString("wm_rem"));
                t8.setText(rs.getString("cmdt_rem"));
                t9.setDate(rs.getDate("reminder"));
                if("Y".equals(rs.getString("p")))
                    cmb1.setSelectedIndex(1);
                if("Y".equals(rs.getString("c")))
                    c2.setSelected(true);
                if(rs.getString("wm").equals("Y")){
                    chwm.setSelected(true);
                }
                if(rs.getString("cmdt").equals("Y")){
                    chcmdt.setSelected(true);
                }
            }

        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this,e.getStackTrace());
        }

    }//GEN-LAST:event_btnhideActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        
    }//GEN-LAST:event_t4ActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        JFileChooser f= new JFileChooser();
        int result=f.showOpenDialog(this);
        ff=f.getSelectedFile().getAbsolutePath();
        img.setText(ff);
    }//GEN-LAST:event_btnActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        if(c2.isSelected()){
            l18.setVisible(false);
            btn.setVisible(false);
            img.setVisible(false);
        }
    }//GEN-LAST:event_c2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ogAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ogAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnhide;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox chcmdt;
    private javax.swing.JCheckBox chwm;
    private javax.swing.JComboBox cmb1;
    private javax.swing.JTextField img;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JLabel l16;
    private javax.swing.JLabel l17;
    private javax.swing.JLabel l18;
    private javax.swing.JLabel l9;
    private javax.swing.JLabel label;
    private java.awt.Panel panel2;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private com.toedter.calendar.JDateChooser t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JComboBox t4;
    private javax.swing.JComboBox t5;
    private javax.swing.JTextArea t7;
    private javax.swing.JTextArea t8;
    private com.toedter.calendar.JDateChooser t9;
    // End of variables declaration//GEN-END:variables
}
