/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p1;

import java.awt.Color;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Situ Singh
 */
public class priSearch extends javax.swing.JFrame {

    /**
     * Creates new form priSearch
     */
    Connection conn=null;
        Statement stmt=null;
        String sql,sql1;
    public priSearch() {
        initComponents();
        Color c=new Color(0,102,102);
        tab1.getColumnModel().getColumn(0).setMaxWidth(50);
        this.getContentPane().setBackground(c);
        DefaultTableModel dm=(DefaultTableModel)tab1.getModel();
        dm.setRowCount(0);
        tab1.setModel(dm);
        try
        {
            String JDBC_DRIVER = "com.mysql.jdbc.Driver";
            String DB_URL = "jdbc:mysql://localhost/dak";
            String USER = "root";
            String PASS = "root";
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(DB_URL,USER,PASS);
            stmt=conn.createStatement();
            sql="select * from pp where p='Y' and c='N';";
            ResultSet rs=stmt.executeQuery(sql);
            int i=0;
            DefaultTableModel tm=(DefaultTableModel)tab1.getModel();
            while(rs.next()){
                if(rs.getBlob("image")!=null){
                Object[] row={++i,rs.getString("date"),rs.getString("letterno"),rs.getString("subject"),rs.getString("recv_from"),"P&P",rs.getString("table_name"),rs.getString("pp_rem"),rs.getString("wm_rem"),rs.getString("cmdt_rem"),"See Image"};
                tm.addRow(row);
                }
                else{
                 Object[] row={++i,rs.getString("date"),rs.getString("letterno"),rs.getString("subject"),rs.getString("recv_from"),"P&P",rs.getString("table_name"),rs.getString("pp_rem"),rs.getString("wm_rem"),rs.getString("cmdt_rem"),"No Image"};
                tm.addRow(row);
                }
            }
           sql1="select * from other where p='Y' and c='N';";
            ResultSet rs1=stmt.executeQuery(sql1);
            while(rs1.next()){
                if(rs1.getBlob("image")!=null){
                Object[] row={++i,rs1.getString("date"),rs1.getString("letterno"),rs1.getString("subject"),rs1.getString("recv_from"),rs1.getString("grp"),"------","------",rs1.getString("wm_rem"),rs1.getString("cmdt_rem"),"See Image"};
                tm.addRow(row);
                }
                else{
                    Object[] row={++i,rs1.getString("date"),rs1.getString("letterno"),rs1.getString("subject"),rs1.getString("recv_from"),rs1.getString("grp"),"------","------",rs1.getString("wm_rem"),rs1.getString("cmdt_rem"),"No Image"};
                    tm.addRow(row);
                }
            }

        }
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        tab1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SNo.", "Date", "Letter No.", "Subject", "Recvd. From", "Group", "Table Name", "P&P Remarks", "WM Remarks", "Cmdt Remarks", "Scanned Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab1.setToolTipText("");
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab1);

        jLabel4.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PRIORITY DAK ");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(507, 507, 507)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 458, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        int row=tab1.rowAtPoint(evt.getPoint());
        int col=tab1.columnAtPoint(evt.getPoint());
        String lno=(String)tab1.getValueAt(row,2);
        try{
            String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
            String DB_URL = "jdbc:mysql://localhost/dak";
            String USER = "root";
            String PASS = "root";
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(DB_URL,USER,PASS);
            stmt=conn.createStatement();
            String sql3 = "select letterno from pp;";
           ResultSet rs=stmt.executeQuery(sql3);
            while(rs.next()){
                
                if(lno.equals(rs.getString("letterno"))){
                    if(col==10){
                        String s=(String)tab1.getValueAt(row,10);
                        if(s.equals("See Image")){
                        try {
                            String lno1=(String)tab1.getValueAt(row,2);
                            scan ob1 =new scan(lno,1);
                            ob1.setVisible(true);
                        } 
                           catch (SQLException | ClassNotFoundException | IOException ex) {
                            Logger.getLogger(ogSearch.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        }
                        else{
                            JOptionPane.showMessageDialog(this,"Oops!! Nothing to show");
                        }
                    }
                    else{
                    ppAdd ob=new ppAdd(lno);
                    ob.setVisible(true); 
                    }
                }
                
               }
            String sql4 = "select letterno from other;";
           ResultSet rs1=stmt.executeQuery(sql4);
            while(rs1.next()){
                if(lno.equals(rs1.getString("letterno"))){
                    if(col==10){
                       String s=(String)tab1.getValueAt(row,10);
                        if(s.equals("See Image")){
                        try {
                            String lno2=(String)tab1.getValueAt(row,2);
                            scan ob1 =new scan(lno,2);
                            ob1.setVisible(true);
                        } catch (SQLException | ClassNotFoundException | IOException ex) {
                            Logger.getLogger(ogSearch.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        }
                        else{
                            JOptionPane.showMessageDialog(this,"Oops!! Nothing to show");
                        }
                    }
                    else{
                    ogAdd ob=new ogAdd(lno);
                    ob.setVisible(true); 
                    }
                }
               }
           
       }
       catch(ClassNotFoundException | SQLException e){
           JOptionPane.showMessageDialog(this,e.getMessage());
       }
    }//GEN-LAST:event_tab1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(priSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new priSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab1;
    // End of variables declaration//GEN-END:variables
}
