/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p1;

import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Situ Singh
 */
public class scan extends javax.swing.JFrame {

    /**
     * Creates new form scan
     */
    
    private ImageIcon format=null;
    String ff=null;
    int s=0;
    byte[] person_image=null;
    BufferedImage im;
    
    public scan() {
        initComponents();
    }

    public scan(String lno,int x) throws SQLException, ClassNotFoundException, IOException {
        initComponents();
         try
      {
            String JDBC_DRIVER = "com.mysql.jdbc.Driver";  
            String DB_URL = "jdbc:mysql://localhost/dak";
            String USER = "root";
            String PASS = "root";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(DB_URL,USER,PASS);
            Statement stmt=conn.createStatement();
            if(x==1){
            String sql="select image from pp where letterno = '"+lno+"';";
            ResultSet rs=stmt.executeQuery(sql);
           while (rs.next()) {
                im=ImageIO.read(rs.getBinaryStream(1));
                im=linearResizeBi(im,900,750);
              }
                ImageIcon image1=new ImageIcon(im);
                scr.setViewportView(new JLabel(image1));
            }
	
        if(x==2){
            String sql="select image from other where letterno = '"+lno+"';";
            ResultSet rs=stmt.executeQuery(sql);
            while (rs.next()) {
                im=ImageIO.read(rs.getBinaryStream(1));
                im=linearResizeBi(im,900,750);
              }
                ImageIcon image1=new ImageIcon(im);
                scr.setViewportView(new JLabel(image1));
            }
        
            if(x==3){
            String sql="select image from adm where letterno = '"+lno+"';";
            ResultSet rs=stmt.executeQuery(sql);
            while (rs.next()) {
                im=ImageIO.read(rs.getBinaryStream(1));
                im=linearResizeBi(im,900,750);
              }
                ImageIcon image1=new ImageIcon(im);
                scr.setViewportView(new JLabel(image1));
            
            }
    }
             catch(ClassNotFoundException | SQLException | IOException e){
                 JOptionPane.showMessageDialog(null,e.getMessage());
                    
                 }
    }
        

    public static BufferedImage linearResizeBi(BufferedImage im, int width, int height) {
        BufferedImage rimg=new BufferedImage(width,height,BufferedImage.TYPE_INT_RGB);
        Graphics2D g=rimg.createGraphics();
        float x=(float)width/im.getWidth();
        float y=(float)height/im.getHeight();
        AffineTransform st=AffineTransform.getScaleInstance(x, y);
        g.drawRenderedImage(im, st);
        g.dispose();
        return rimg;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scr = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scr, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new scan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scr;
    // End of variables declaration//GEN-END:variables
}
